apiVersion: v2
name: workshop-test
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: app-dev-lab
    repository: oci://ghcr.io/noale1/helm
    version: "1.0.1"
    alias: deploy1
  - name: app-dev-lab
    repository: oci://ghcr.io/noale1/helm
    version: 1.0.1
    alias: deploy2
version: 1.0.1
appVersion: "1.0.0"