ReplicaNumber: 3

containers:
  containerPort: 8080
  image: 'quay.io/noale/helloworld'
  tag: 'chart_v1cd'

service:
  servicePort: 8080

probes:
  readiness:
    path: /health/readiness
    initialDelaySeconds: 1 # the time is waiting befor testing the application path
    timeoutSeconds: 1 # the time for timeout
    periodSeconds: 10 # the abount of time to wait between checks
    successThreshold: 1 # count to decalre seccessfull 
    failureThreshold: 3
  liveness:
    path: /health/liveliness
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

volume:
  mount:
    path: /tmp/html